/*
 * Book's Story — free and open-source Material You eBook reader.
 * Copyright (C) 2024-2025 Acclorite
 * SPDX-License-Identifier: GPL-3.0-only
 */

package com.classictoon.novel.data.mapper

import com.classictoon.novel.data.remote.dto.RemoteBookResponse
import com.classictoon.novel.data.local.dto.BookEntity
import com.classictoon.novel.domain.library.category.Category

fun RemoteBookResponse.toBookEntity(): BookEntity {
    return BookEntity(
        id = 0, // Will be auto-generated by Room
        title = this.title,
        author = this.author,
        description = null, // Not provided by API
        filePath = "", // Will be set after download
        scrollIndex = 0,
        scrollOffset = 0,
        progress = 0f,
        image = this.cover,
        category = mapCategory(this.category),
        remoteBookId = this.bookId
    )
}

private fun mapCategory(category: String): Category {
    return when (category.lowercase()) {
        "fiction" -> Category.FICTION
        "non-fiction" -> Category.NON_FICTION
        "mystery" -> Category.MYSTERY
        "romance" -> Category.ROMANCE
        "sci-fi", "science fiction" -> Category.SCIENCE_FICTION
        "fantasy" -> Category.FANTASY
        "biography" -> Category.BIOGRAPHY
        "history" -> Category.HISTORY
        "self-help" -> Category.SELF_HELP
        else -> Category.OTHER
    }
}
